"""add relationship to db models

Revision ID: 3018e4a6c189
Revises: a29bda5189f6
Create Date: 2021-08-01 10:53:23.437537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3018e4a6c189'
down_revision = 'a29bda5189f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.VARCHAR(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DATETIME(), nullable=True))
    # ### end Alembic commands ###
